# Site settings
title: nowhere-man's blog
keywords: nowhere-man
description: >-
  He's a real nowhere man
  sitting in his nowhere land
  making all his nowhere plans
  for nobody
url: "https://nowhere-man.github.io/"
page_no_title: "nowhere-man's blog"
author: nowhere-man

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]

plugins:
  - jekyll-paginate

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: false
google_search: false

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 关于
    directory: about/
    icon: icon-about
