title: 我的技术分享博客
description: >-
  欢迎来到我的技术分享博客

permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
